name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.5, 8.4, 8.3, 8.2]
        laravel: [13.*, 12.*, 11.*]
        exclude:
            -   laravel: 13.*
                php: 8.3
            -   laravel: 13.*
                php: 8.2

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer install --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit
